### ISSUE TITLE
API: api/profile/current/set-password/

### ISSUE THREAD

**Issue by angelocapone** [tolgayildizz/laravel-5.7-email-verification-and-auth-via-api#1]
Hi Tolda,
Just wanted to point out that regarding this API:
http://127.0.0.1:8000/api/profile/current/set-password/

the email field is not required.

Thank you,
Angelo

**Comment by tolgayildizz** [comment]
Thank you, Mr. Angelo. I'm updating the readme file. Thank you again for your feedback.
